name: Desktop C++ Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:	
    - uses: actions/checkout@v2
    - name: make test
      run: make run_all_tests
      working-directory: ./Desktop-Application
    - name: make clean
      run: make clean
      working-directory: ./Desktop-Application
